### ISSUE TITLE
 Viruses inside the Programm

### ISSUE THREAD

**Issue by RKLGmbH** [Hackinside/PS4-CAMERA-DRIVERS#2]
There is something that force Chrome to give an virus alert

**Comment by Hackinside** [comment]
> 
> 
> There is something that force Chrome to give an virus alert

If you go to the download list, select the file, choose to keep it. It isn't a virus. Because the file isn't signed it gives you a false positive. 
Maybe try Mozilla Firefox.

**Comment by RKLGmbH** [comment]
It helped. I am sorry thank you for your help and your software. Have a nice day :-)
