### ISSUE TITLE
Camera not turning on

### ISSUE THREAD

**Issue by thomaspancake33** [Hackinside/PS4-CAMERA-DRIVERS#6]
I downloaded everything and it said the device was USB Camera-OV580 but when I turned my camera on the screen is just black, its showing its detecting it as a camera and playing it but its just giving me a pitch black feed.

**Comment by Hackinside** [comment]
Try play with the camera settings. Selecting auto exposure may help.

**Comment by thomaspancake33** [comment]
I played around with some setting and it started working, thank you.
